### PR TITLE
Sse task

### PR DESCRIPTION
**Pull request by thaistcosta**
For this one....

I implemented SSE for the task on create and on update... which means that the user is going to see live data.

Also, changed a little bit of the projects and dashboard queries.

Changed the schema for Feed and also added delete cascade.

I think thats all

besitos 🍪 🦞

### CODE REVIEW

**Review by alexandra-plana — APPROVED** [review]
isso é incrível! você é uma deusa ✨

**Comment by thaistcosta** [comment]
heeelloo

``
test
``

**Review by lexarisa — APPROVED** [review]
ok, i feel like im not doing enough work after seeing this :'3 
Great job!!! <3

**Comment by thaistcosta** [comment]
```
<html> Hello World</html>
```

**Pull request merged**
